### ISSUE TITLE
Observaciones

### ISSUE THREAD

**Issue by GuilleGonz8** [MatiasSilvaAreal/mercadoLiebre#2]
[issues matias.docx](https://github.com/MatiasSilvaAreal/mercadoLiebre/files/13326866/issues.matias.docx)

Ahí en ese word están las observaciones relacioandas a lo que pedían los pdfs en particular configuraciones especificas.

Ahora con respecto a la vista desde cada dispositivo desde el navegador, esto me fijaria:

- Desde la perspectiva de movil 425px los articulos se ven alineados hacia la izquierda cuando deberían estar centrados.
- Los iconos del footer estan de color negro cuando creo que deberian ser azules y la letra de esos textos gris
- En la vista de tablet (768px en adelante) los articulos se ven muy separados entre si, pero está bien que aparezcan de 2 y los iconos del footer siguen negros junto con la letra.
- En la vista de 1024px en adelante ya se deberían visualizar los articulos en una sola fila de 4, siguen viendose 2 por fila y muy separados, lo mismo que lo anterior iconos y color de letra del footer
- Por el resto todo se ve bien es decir header y tambien a partir de los 1200px por tu media queries ya todas las observaciones anteriores se resuelven, pero deberían resolverse desde 768px en adelante
- Formulario de registro se ve bien en todas las vistas, solo fijate las observaciones que te deje en el word con respecto a la validacion
- El formulario de login en la vista de 425px (movil), el footer parece estar fijo y tapar el formulario (fijarse eso), luego en las demas vistas se ve todo perfecto.

**Comment by MatiasSilvaAreal** [comment]
Resuelto. Algunos detalles no se modificaron por motivos estéticos que considero quedan mejor
